# Generated by Django 4.0.4 on 2022-05-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_speaker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journey'),
        ),
    ]
