# Generated by Django 4.0.4 on 2022-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journey_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='is_the_first_date',
            field=models.BooleanField(default=False),
        ),
    ]
