# Generated by Django 4.0.4 on 2022-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journey_is_the_first_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='role',
            field=models.CharField(default='Speaker', max_length=50, null=True),
        ),
    ]
