# Generated by Django 4.0.3 on 2022-05-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='images/speakers/')),
                ('post', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('Speaker', 'speaker'), ('Organizer', 'organizer'), ('Contributor', 'contributor')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('about', models.TextField()),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='directed_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.journey'),
        ),
        migrations.AlterField(
            model_name='event',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.edition'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.edition'),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AddField(
            model_name='speakerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AddField(
            model_name='speakerevent',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
    ]
