# Generated by Django 4.0.4 on 2022-05-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journey',
            new_name='Day',
        ),
    ]
