# Generated by Django 4.0.4 on 2022-05-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_journey_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
